default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_MAX_POOL") { 5 } %>
  database: app_<%= ENV["RACK_ENV"] %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
